myblog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

"""
accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
"""

urlpatterns = [
    path('blog/', views.request_index, name="home"),
    path('blog/book-review/', views.ReviewListView.as_view(), name="book-review"),
    path('blog/book/<int:pk>/', views.BookDetailView.as_view(), name="book-detail"),
    path('login/', auth_views.LoginView.as_view()),
    path('logout/', auth_views.LogoutView.as_view()),

    # 템플릿 이름을 바꿔줄 수 있다. 
    # path('accounts/login/', auth_views.LoginView.as_view(template_name='myapp/login.html')), 
    # path('password_change/', auth_views.PasswordChangeView.as_view(template_name='change-password.html')),
]

mysite/urls.py
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. (urlpatterns 리스트는 url들을 뷰로 라우팅한다.)

Examples:
Function views (함수형 view라면? )
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views (클래스형 view라면? )
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf (다른 URLconf를 포함하려면?)
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))

URLconf는 뭘까?
- settings.py에 최상위 url이 지정되어 있다 :  ROOT_URLCONF = 'mysite.urls'
- 특정 url과 뷰를 매핑한다.
- Django 서버로 Http 요청이 들어올 때마다, URLConf 매핑 List 를 처음부터 끝까지 순차적으로 훝으며 검색
- 매칭되는 URL Rule 을 찾지못했을 경우, 404 Page Not Found 응답을 발생
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('myblog.urls', 'myblog'), namespace="myblog")), #include( (앱 urls.py, 앱 이름), namespace )
    path('', include(('randTeam.urls', 'randTeam'), namespace="randTeam" )),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

myblog/models.py
from django.db import models
from django.utils import timezone #시간, 날짜와 관련된 모듈 

# Create your models here.
class ReadingList(models.Model) :

    BOOK_SCORE = ( #왼쪽이 보여질 것 / 오른쪽이 관리자 페이지에 나올 것.
        ('Awesome', 'Awesome'),
        ('Boring', 'Boring'), 
        ('Choigo', 'Choigo'),
        ('Fuck that', 'Fuck that'),
    )

    #책 제목 
    title = models.CharField(max_length=50)

    #서평 
    review = models.TextField(help_text="가차없이 적어라!!")

    #평점
    score = models.CharField(
        max_length=15,
        choices=BOOK_SCORE,
        default='Awesome',
    )

    #책 정보
    book_info_url = models.URLField() #url이라고 바꿔주기 

    #시작일, 완독일
    start_date = models.DateTimeField(blank=True, null=True) 
    finished_date = models.DateTimeField(
        auto_now_add=True) #편집 불가. 자동으로 오늘 날짜로 맞춘다. #편집 가능하고, 오늘 날짜로 하고 싶으면 datetime.now()를 쓸 것.

    def __str__(self) : 
        return self.title 
    
class Book(models.Model) :

    # title = models.OneToOneField(ReadingList, on_delete=models.CASCADE)
    title = models.ForeignKey('ReadingList', on_delete=models.CASCADE)
    writer = models.CharField(max_length=50)
    plot = models.TextField(help_text="줄거리")
    published_year = models.DateTimeField(blank=True)

    def __str__(self) :
        return '%s :  %s ' % ( self.title, self.writer)

myblog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse #0 FBV
from django.contrib.auth import views #1
from django.template.response import TemplateResponse #2
from myblog.models import ReadingList, Book
from django.views.generic import ListView, DetailView

# Create your views here.
def request_index(request):
    return render(request, "myblog/index.html")


def password_change(request):
    template_response = views.password_change(request)
    # Do something with `template_response`
    return template_response


#리스트 뷰 만들기 
class ReviewListView(ListView): 
    """
	ListView 디폴트 지정 속성 : 컨텍스트를 쓸 때, model만 쓸 때 
	1) 컨텍스트 변수 : object_list
	2) 템플릿 파일 : readinglist_list.html (모델명 소문자_list.html)
	"""
    model = ReadingList
    template_name = 'myblog/review_list.html'
    paginate_by = 1

#디테일 뷰 만들기
class BookDetailView(DetailView):
    model = Book # 해당 모델 - URLConf 의 PK 변수를 활용하여 해당 모델의 특정 record를 컨텍스트 변수(object)에 담는다.
    template_name = 'myblog/book_detail.html' # 디폴트 템플릿명: <app_label>/<model_name>_detail.html
    context_object_name = 'book' # 디폴트 컨텍스트 변수명 :  object 이름 (book)

myblog/templates/myblog/book_detail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
    <h2>{{ book.title }}</h2>

    <p>
        {{ book.plot }}

    </p>




</body>
</html>

myblog/templates/myblog/change-password.html
<h1>Hello</h1>

myblog/templates/myblog/index.html
<H1>HEllO World</H1>
<H1>HEllO World</H1>
<H1>HEllO World</H1>
<H1>HEllO World</H1>
<H1>HEllO World</H1>

myblog/templates/myblog/review_list.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>

    <ul>
        {% if user.is_active %}
          <li><a href="{%url 'login' %}"> {{user.username}}</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{%url 'login' %}"> Login</a></li>
          <li><a href="{% url 'admin:index' %}">Admin</a></li>
        {% endif %}
      </ul>

      
      



    
    <h2>서평 목록</h2>

    {% if object_list %}
    <ul>
      {% for r in object_list  %}
        <!-- 프로젝트 폴더에 등록한 app의 name 라벨 : url패턴에 있는 뷰 name-->
        <a href={% url 'myblog:book-detail' r.id %}>{{ r.title }}</a> | {{ r.score }}<br>
        <!-- <a href={{ r.book_info_url }}>{{ r.title }}</a> | {{ r.score }}<br> -->
        {{ r.review }} <br><br>
      {% endfor %}
    </ul>
    {% endif %}
    
    
    <!-- bootstrap style을 적용한다. -->
    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <!-- url : /?page=1 -->
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li> 
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}

      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}

    </ul>

    {% endif %}

</body>
</html>